# Generated by Django 4.0.2 on 2022-03-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_profile_id_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
