# Generated by Django 4.0.2 on 2022-03-23 18:56

import django.core.validators
from django.db import migrations, models
import pintereso.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), pintereso.web.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), pintereso.web.validators.only_letters_validator]),
        ),
    ]
